---
apiVersion: v1
kind: Secret
metadata:
  name: ead-secrets
  namespace: ead-application
type: Opaque
stringData:
  # Database Credentials
  POSTGRES_PASSWORD: "dila2001"
  
  # JWT Secret
  JWT_SECRET: "eadSecretKeyForJWTTokenGeneration2024!@#MinimumThirtyTwoCharacters"
  
  # Cloudinary Credentials
  CLOUDINARY_CLOUD_NAME: "your-cloud-name"
  CLOUDINARY_API_KEY: "your-api-key"
  CLOUDINARY_API_SECRET: "your-api-secret"
  
  # Gemini API Key
  GEMINI_API_KEY: "AIzaSyCaj8GEIEvhLXEc9G5Us2eyc0MxkF2SchY"
  
  # Email Credentials
  SPRING_MAIL_USERNAME: "behaniw2002@gmail.com"
  SPRING_MAIL_PASSWORD: "efyb foni oxka npia"
